// vgi-rpc-typescript Arrow facade. Mirrors vgi-typescript's facade so types
// flow freely between the two packages. Backend selected via `#vgi-rpc-arrow`
// in package.json's `imports` field (workerd/worker/browser → impl-flechette,
// default → impl-arrowjs).

export {
  backend,
  batchFromColumnData,
  batchFromColumns,
  binary,
  bool,
  // Construction
  columnFromArray,
  conformBatchToSchema,
  createIncrementalEncoder,
  dateDay,
  decimal,
  deserializeBatch,
  deserializeSchema,
  dictionary,
  durationMicro,
  emptyBatchWithMetadata,
  emptyColumnData,
  field,
  fixedSizeBinary,
  float32,
  float64,
  int8,
  int16,
  int32,
  int64,
  isOpaqueData,
  largeBinary,
  largeUtf8,
  list,
  map,
  // Type factories
  nullType,
  schema,
  serializeBatch,
  serializeBatches,
  // IPC
  serializeSchema,
  singleRowBatch,
  singleRowBatchWithMetadata,
  struct,
  timeMicro,
  timestampMicro,
  uint8,
  uint16,
  uint32,
  uint64,
  utf8,
  withBatchMetadata,
} from "#vgi-rpc-arrow";

export {
  isBatch,
  isBinary,
  isBool,
  isDate,
  isDecimal,
  isDictionary,
  isDuration,
  isFixedSizeBinary,
  isFloat,
  isInt,
  isLargeBinary,
  isLargeUtf8,
  isList,
  isMap,
  isNull,
  isStruct,
  isTime,
  isTimestamp,
  isUtf8,
  TypeId,
} from "./predicates.js";
export type {
  IncrementalEncoder,
  VgiBackendInfo,
  VgiBatch,
  VgiColumn,
  VgiColumnData,
  VgiDataType,
  VgiField,
  VgiSchema,
  VgiTypeId,
} from "./types.js";
