/**
 * @import { Table } from '../table.js';
 * @import { CompressionType_ } from '../types.js';
 * @import { Sink } from './sink.js';
 */
import { Type, UnionMode } from '../constants.js';
import { compressBuffer, getCompressionCodec, missingCodec } from '../compression.js';
import { Column } from '../column.js';
import { Table as Table_ } from '../table.js';
import { encodeIPC } from './encode-ipc.js';
import { assembleDictionaryBatches, assembleSchema, tableToIPC } from './table-to-ipc.js';

/**
 * Encode multiple Arrow tables into a single Arrow IPC stream.
 *
 * Each input table contributes its record batches to the output stream in
 * order — the result is a multi-batch IPC stream that downstream readers
 * (PyArrow, arrow-js, flechette itself) consume in one pass. All input
 * tables MUST share an equivalent schema (same field count and names; the
 * first table's schema is used for the output).
 *
 * Equivalent to concatenating multiple single-table IPC streams except the
 * intermediate schema headers and EOS markers are stripped — naive
 * concatenation produces a stream with multiple EOS markers, which causes
 * readers to stop after the first table's batches.
 *
 * @param {Table[]} tables The Arrow tables to encode (must share a schema).
 * @param {object} [options] Encoding options.
 * @param {Sink} [options.sink] IPC byte consumer.
 * @param {'stream' | 'file'} [options.format] Arrow stream or file format.
 * @param {CompressionType_ | null} [options.codec] Compression codec to apply.
 * @returns {Uint8Array | null} The generated bytes (for an in-memory sink)
 *  or null (if using a sink that writes bytes elsewhere).
 */
export function tablesToIPC(tables, options) {
  if (!tables || tables.length === 0) {
    throw new Error('tablesToIPC requires at least one table');
  }
  // Per-table path stays simple — the per-record-batch custom_metadata
  // pulled from `t._vgiRecordMetadata` flows through `tableToIPC`'s
  // batchMetadata option.
  if (tables.length === 1) {
    const tm = tables[0]?._vgiRecordMetadata;
    const opts = tm && !options?.batchMetadata
      ? { ...(options ?? {}), batchMetadata: [tm] }
      : options;
    return tableToIPC(tables[0], opts);
  }
  // Multi-table path: when every input table contributes ≥1 actual
  // record batch, the standard `concatTables → tableToIPC` flow handles
  // dictionaries / batch ordering / metadata correctly (per-table
  // `_vgiRecordMetadata` is honored by `tableToIPC`'s positional
  // batchMetadata option). When at least one input is metadata-only
  // (vgi-rpc log/EXCEPTION shape with zero column data), concat would
  // drop it and scramble positions — fall back to the manual
  // assembly path that synthesises empties at the right positions.
  const hasEmptyWithMd = tables.some(
    (t) => (t?.children?.[0]?.data?.length ?? 0) === 0 && t?._vgiRecordMetadata,
  );
  if (!hasEmptyWithMd) {
    // Build positional batchMetadata from per-table _vgiRecordMetadata.
    const md = [];
    for (const t of tables) {
      const tm = t?._vgiRecordMetadata;
      const n = t?.children?.[0]?.data?.length ?? 0;
      for (let i = 0; i < n; i++) md.push(i === 0 ? tm : undefined);
    }
    const opts = md.some((m) => m && m.size > 0)
      ? { ...(options ?? {}), batchMetadata: md }
      : options;
    return tableToIPC(concatTables(tables), opts);
  }
  return multiTableToIPC(tables, options);
}

/** Assemble + encode IPC for a sequence of Tables sharing a schema,
 *  preserving per-table batch positions even when some tables are
 *  metadata-only with zero column-data batches. */
function multiTableToIPC(tables, options) {
  const id = options?.codec;
  const codec = getCompressionCodec(id);
  if (id != null && !codec) throw new Error(missingCodec(id));

  const headFields = tables[0].schema.fields;
  // Per-record-batch entries accumulated in stream order.
  /** @type {any[]} */
  const records = [];
  /** @type {(Map<string,string> | undefined)[]} */
  const batchMetadata = [];

  for (const t of tables) {
    const tm = t?._vgiRecordMetadata;
    const cols = t.children;
    // Number of actual record batches this table contributes (first
    // column's data array length — all columns share batch shape).
    const actualBatches = cols?.[0]?.data?.length ?? 0;

    if (actualBatches > 0) {
      for (let i = 0; i < actualBatches; i++) {
        const rec = assembleSingleBatch(cols, i, codec);
        records.push(rec);
        batchMetadata.push(i === 0 ? tm : undefined);
      }
    } else if (tm) {
      // Empty data + metadata → synthesise one empty record batch with
      // proper FieldNodes / region descriptors derived from the schema.
      const nodes = [];
      const regions = [];
      const variadic = [];
      for (const f of headFields) {
        _appendEmptyNodes(f.type, nodes, regions, variadic);
      }
      records.push({ length: 0, nodes, regions, variadic, buffers: [], byteLength: 0 });
      batchMetadata.push(tm);
    }
    // Tables with no data and no metadata are dropped entirely (same
    // as legacy concatTables behaviour).
  }

  // Apply metadata at the right positions.
  for (let i = 0; i < records.length; i++) {
    const md = batchMetadata[i];
    if (md && md.size > 0) records[i].metadata = md;
  }

  // Assemble dictionary batches + resolved schema. We use the columns
  // of the first table that contributes actual data — its Dictionary
  // columns hold the canonical dictionaries that the encoder needs to
  // emit BEFORE any record batch that references them. Without this,
  // a schema like `(int64, dictionary<int16, utf8>)` encodes the
  // RecordBatch fine but pyarrow rejects the stream with "Dictionary
  // field not found".
  const dataTable = tables.find((t) => (t?.children?.[0]?.data?.length ?? 0) > 0);
  let dictionaries = [];
  let idMap = new Map();
  if (dataTable) {
    const r = assembleDictionaryBatches(dataTable.children, codec);
    dictionaries = r.dictionaries;
    idMap = r.idMap;
  }
  const schema = assembleSchema(tables[0].schema, idMap);

  const data = { schema, dictionaries, records };
  return encodeIPC(data, { ...options, codec: id }).finish();
}

/** Assemble one record batch (`columns`'s batchIndex-th batch) into the
 *  RecordBatch struct flechette's encoder expects. Mirrors the
 *  `assembleRecordBatch` helper inside `table-to-ipc.js`. */
function assembleSingleBatch(columns, batchIndex, codec) {
  let byteLength = 0;
  const nodes = [];
  const regions = [];
  const buffers = [];
  const variadic = [];

  const ctx = {
    node(length, nullCount) { nodes.push({ length, nullCount }); },
    buffer(b) {
      const bytes = new Uint8Array(b.buffer, b.byteOffset, b.byteLength);
      const buf = codec ? compressBuffer(bytes, codec) : bytes;
      const length = buf.byteLength;
      regions.push({ offset: byteLength, length });
      buffers.push(buf);
      byteLength += ((length + 7) & ~7);
    },
    variadic(length) { variadic.push(length); },
    children(type, batch) {
      type.children.forEach((field, index) => {
        _visit(field.type, batch.children[index], ctx);
      });
    },
  };

  for (const column of columns) {
    _visit(column.type, column.data[batchIndex], ctx);
  }
  return { byteLength, nodes, regions, variadic, buffers };
}

/** Recursive per-field visitor mirroring `table-to-ipc.js#visit`. Lifted
 *  here so the multi-table path doesn't need to import private helpers. */
function _visit(type, batch, ctx) {
  const { typeId } = type;
  ctx.node(batch.length, batch.nullCount);
  if (typeId === Type.Null) return;
  switch (typeId) {
    case Type.Bool:
    case Type.Int:
    case Type.Time:
    case Type.Duration:
    case Type.Float:
    case Type.Date:
    case Type.Timestamp:
    case Type.Decimal:
    case Type.Interval:
    case Type.FixedSizeBinary:
    case Type.Dictionary:
      ctx.buffer(batch.validity); ctx.buffer(batch.values); return;
    case Type.Utf8:
    case Type.LargeUtf8:
    case Type.Binary:
    case Type.LargeBinary:
      ctx.buffer(batch.validity); ctx.buffer(batch.offsets); ctx.buffer(batch.values); return;
    case Type.BinaryView:
    case Type.Utf8View:
      ctx.buffer(batch.validity); ctx.buffer(batch.values);
      ctx.variadic(batch.data.length);
      batch.data.forEach((b) => ctx.buffer(b));
      return;
    case Type.List:
    case Type.LargeList:
    case Type.Map:
      ctx.buffer(batch.validity); ctx.buffer(batch.offsets);
      ctx.children(type, batch); return;
    case Type.ListView:
    case Type.LargeListView:
      ctx.buffer(batch.validity); ctx.buffer(batch.offsets); ctx.buffer(batch.sizes);
      ctx.children(type, batch); return;
    case Type.FixedSizeList:
    case Type.Struct:
      ctx.buffer(batch.validity); ctx.children(type, batch); return;
    case Type.RunEndEncoded:
      ctx.children(type, batch); return;
    case Type.Union: {
      ctx.buffer(batch.typeIds);
      if (type.mode === UnionMode.Dense) ctx.buffer(batch.offsets);
      ctx.children(type, batch);
      return;
    }
    default:
      throw new Error(`Unsupported type: ${typeId}`);
  }
}

/** Mirror of the `appendEmptyNodes` helper in table-to-ipc.js — kept
 *  here to avoid cross-file imports for an internal helper. */
function _appendEmptyNodes(type, nodes, regions, variadic) {
  nodes.push({ length: 0, nullCount: 0 });
  if (type.typeId === Type.Null) return;
  switch (type.typeId) {
    case Type.Bool:
    case Type.Int:
    case Type.Time:
    case Type.Duration:
    case Type.Float:
    case Type.Date:
    case Type.Timestamp:
    case Type.Decimal:
    case Type.Interval:
    case Type.FixedSizeBinary:
    case Type.Dictionary:
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      return;
    case Type.Utf8:
    case Type.LargeUtf8:
    case Type.Binary:
    case Type.LargeBinary:
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      return;
    case Type.BinaryView:
    case Type.Utf8View:
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      variadic.push(0);
      return;
    case Type.List:
    case Type.LargeList:
    case Type.Map:
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      type.children?.forEach((c) => _appendEmptyNodes(c.type, nodes, regions, variadic));
      return;
    case Type.FixedSizeList:
    case Type.Struct:
      regions.push({ offset: 0, length: 0 });
      type.children?.forEach((c) => _appendEmptyNodes(c.type, nodes, regions, variadic));
      return;
    default:
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
  }
}

// concatTables is exported below — `tablesToIPC` is just a thin wrapper that
// concatenates first then encodes.

/**
 * Concatenate multiple Tables (sharing a schema) row-wise into a single
 * Table whose Columns carry every input's batches in order. Existing batch
 * boundaries are preserved — if input table A has 2 batches and B has 3,
 * the result has 5 batches in `[A0, A1, B0, B1, B2]` order. (When you then
 * encode via `tablesToIPC` / `tableToIPC`, each batch becomes one IPC
 * record message, so the wire stream has 5 records.)
 *
 * The new Table reuses the first input's schema and per-column types.
 * Inputs must agree on field count and field names; type compatibility
 * beyond that is the caller's responsibility.
 *
 * @param {Table[]} tables The Arrow tables to concatenate.
 * @returns {Table} A new Table with batches drawn from every input in order.
 */
export function concatTables(tables) {
  if (!tables || tables.length === 0) {
    throw new Error('concatTables requires at least one table');
  }
  if (tables.length === 1) return tables[0];

  const head = tables[0];
  const headFields = head.schema.fields;

  // Validate schema compatibility before allocating.
  for (let i = 1; i < tables.length; i++) {
    const fields = tables[i].schema.fields;
    if (fields.length !== headFields.length) {
      throw new Error(
        `concatTables: table at index ${i} has ${fields.length} fields, ` +
        `expected ${headFields.length}`,
      );
    }
    for (let f = 0; f < headFields.length; f++) {
      if (fields[f].name !== headFields[f].name) {
        throw new Error(
          `concatTables: table at index ${i} field[${f}] name is ` +
          `'${fields[f].name}', expected '${headFields[f].name}'`,
        );
      }
    }
  }

  // For each column position, concatenate the per-table batches into a
  // single Column. The first table's column type is authoritative; other
  // tables' batches are appended assuming type-compatibility.
  const mergedChildren = headFields.map((_, colIdx) => {
    const headCol = head.children[colIdx];
    const allBatches = [];
    for (const t of tables) {
      const col = t.children[colIdx];
      for (const b of col.data) allBatches.push(b);
    }
    return new Column(allBatches, headCol.type);
  });

  return new Table_(head.schema, mergedChildren);
}
