/**
 * @import { Batch, DictionaryBatch } from '../batch.js';
 * @import { Column } from '../column.js';
 * @import { Table } from '../table.js';
 * @import { Codec, CompressionType_, DataType, RecordBatch, Schema, TypedArray } from '../types.js';
 * @import { Sink } from './sink.js';
 */
import { compressBuffer, getCompressionCodec, missingCodec } from '../compression.js';
import { Type, UnionMode } from '../constants.js';
import { invalidDataType } from '../data-types.js';
import { encodeIPC } from './encode-ipc.js';

/**
 * Encode an Arrow table into Arrow IPC binary format.
 * @param {Table} table The Arrow table to encode.
 * @param {object} options Encoding options.
 * @param {Sink} [options.sink] IPC byte consumer.
 * @param {'stream' | 'file'} [options.format] Arrow stream or file format.
 * @param {CompressionType_ | null} [options.codec] Compression codec to apply.
 * @returns {Uint8Array | null} The generated bytes (for an in-memory sink)
 *  or null (if using a sink that writes bytes elsewhere).
 */
export function tableToIPC(table, options) {
  // accept a format string option for Arrow-JS compatibility
  if (typeof options === 'string') {
    options = { format: options };
  }

  // resolve compression codec
  const id = options?.codec;
  const codec = getCompressionCodec(id);
  if (id != null && !codec) throw new Error(missingCodec(id));

  const columns = table.children;
  checkBatchLengths(columns);

  const { dictionaries, idMap } = assembleDictionaryBatches(columns, codec);
  const records = assembleRecordBatches(columns, codec);
  const schema = assembleSchema(table.schema, idMap);

  // Per-record-batch custom_metadata — Arrow IPC Message field 4. The
  // caller threads in an array (indexed by batch position) via
  // `options.batchMetadata`; encodeIPC attaches it during message
  // emission. Absent / undefined entries encode as no metadata, matching
  // the pre-feature behaviour for plain data batches.
  const batchMetadata = options?.batchMetadata;
  if (batchMetadata) {
    // Synthesise empty record batches for metadata entries past
    // `records.length`. Two shapes flow here:
    //  - zero-field schema (vgi-rpc EXCEPTION/log batch): no FieldNodes,
    //    no regions. Just metadata.
    //  - schema with fields but no actual column data (vgi-rpc result
    //    schema receiving an error path): emit one FieldNode per field
    //    with length=0/nullCount=0 + the validity/offset/value regions
    //    each type would consume. Without these the wire batch's body
    //    layout disagrees with what pyarrow expects for the schema.
    while (records.length < batchMetadata.length) {
      const nodes = [];
      const regions = [];
      const variadic = [];
      for (const f of schema.fields) {
        // Recursive node walker — every (nested) field gets its own
        // FieldNode + region set.
        appendEmptyNodes(f.type, nodes, regions, variadic);
      }
      records.push({ length: 0, nodes, regions, variadic, buffers: [], byteLength: 0 });
    }
    for (let i = 0; i < records.length; i++) {
      const md = batchMetadata[i];
      if (md && md.size > 0) records[i].metadata = md;
    }
  }

  const data = { schema, dictionaries, records };
  return encodeIPC(data, { ...options, codec: id }).finish();
}

/**
 * Append FieldNodes + region descriptors for a length-0 column of `type`.
 * Mirrors `visit()`'s type → buffer mapping but emits zero-sized regions
 * so the synthesised empty record batch survives schema validation on
 * the reader side (pyarrow checks the buffer count per field).
 *
 * Used by `tableToIPC` to synthesise metadata-only RecordBatch messages
 * for vgi-rpc's EXCEPTION / log batches that carry status info on a
 * non-empty schema without any actual rows.
 */
function appendEmptyNodes(type, nodes, regions, variadic) {
  nodes.push({ length: 0, nullCount: 0 });
  if (type.typeId === Type.Null) return;
  switch (type.typeId) {
    case Type.Bool:
    case Type.Int:
    case Type.Time:
    case Type.Duration:
    case Type.Float:
    case Type.Date:
    case Type.Timestamp:
    case Type.Decimal:
    case Type.Interval:
    case Type.FixedSizeBinary:
    case Type.Dictionary:
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      return;
    case Type.Utf8:
    case Type.LargeUtf8:
    case Type.Binary:
    case Type.LargeBinary:
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      return;
    case Type.BinaryView:
    case Type.Utf8View:
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      variadic.push(0);
      return;
    case Type.List:
    case Type.LargeList:
    case Type.Map:
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      type.children?.forEach((c) => appendEmptyNodes(c.type, nodes, regions, variadic));
      return;
    case Type.ListView:
    case Type.LargeListView:
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
      type.children?.forEach((c) => appendEmptyNodes(c.type, nodes, regions, variadic));
      return;
    case Type.FixedSizeList:
    case Type.Struct:
      regions.push({ offset: 0, length: 0 });
      type.children?.forEach((c) => appendEmptyNodes(c.type, nodes, regions, variadic));
      return;
    case Type.RunEndEncoded:
      type.children?.forEach((c) => appendEmptyNodes(c.type, nodes, regions, variadic));
      return;
    case Type.Union:
      regions.push({ offset: 0, length: 0 });
      if (type.mode === UnionMode.Dense) {
        regions.push({ offset: 0, length: 0 });
      }
      type.children?.forEach((c) => appendEmptyNodes(c.type, nodes, regions, variadic));
      return;
    default:
      // Best-effort: 2-buffer fallback. Unknown types in a vgi-rpc
      // error/log batch are rare; the worst case is a reader rejection.
      regions.push({ offset: 0, length: 0 });
      regions.push({ offset: 0, length: 0 });
  }
}

function checkBatchLengths(columns) {
  const n = columns[0]?.data.map(d => d.length);
  columns.forEach(({ data }) => {
    if (data.length !== n.length || data.some((b, i) => b.length !== n[i])) {
      throw new Error('Columns have inconsistent batch sizes.');
    }
  });
}

/**
 * Create a new assembly context.
 * @param {Codec} [codec] Optional buffer compression codec.
 */
function assembleContext(codec) {
  let byteLength = 0;
  const nodes = [];
  const regions = [];
  const buffers = [];
  const variadic = [];
  return {
    /**
     * @param {number} length
     * @param {number} nullCount
     */
    node(length, nullCount) {
      nodes.push({ length, nullCount });
    },
    /**
     * @param {TypedArray} b
     */
    buffer(b) {
      const bytes = new Uint8Array(b.buffer, b.byteOffset, b.byteLength);
      const buf = codec ? compressBuffer(bytes, codec) : bytes;
      const length = buf.byteLength;
      regions.push({ offset: byteLength, length });
      buffers.push(buf);
      byteLength += ((length + 7) & ~7); // align to padding
    },
    /**
     * @param {number} length
     */
    variadic(length) {
      variadic.push(length);
    },
    /**
     * @param {DataType} type
     * @param {Batch} batch
     */
    children(type, batch) {
      // @ts-ignore
      type.children.forEach((field, index) => {
        visit(field.type, batch.children[index], this);
      });
    },
    /**
     * @returns {RecordBatch}
     */
    done() {
      return { byteLength, nodes, regions, variadic, buffers };
    }
  };
}

/**
 * Assemble dictionary batches and their unique ids.
 * @param {Column[]} columns The table columns.
 * @param {Codec} [codec] Optional buffer compression codec.
 * @returns {{
 *    dictionaries: DictionaryBatch[],
 *    idMap: Map<DataType, number>
 *  }}
 *  The assembled dictionary batches and a map from dictionary column
 *  instances to dictionary ids.
 */
function assembleDictionaryBatches(columns, codec) {
  const dictionaries = [];
  const dictMap = new Map;
  const idMap = new Map;
  let id = -1;

  // track dictionaries, key by dictionary column, assign ids
  const visitor = dictionaryColumn => {
    if (!dictMap.has(dictionaryColumn)) {
      dictMap.set(dictionaryColumn, ++id);
      for (let i = 0; i < dictionaryColumn.data.length; ++i) {
        dictionaries.push({
          id,
          isDelta: i > 0,
          data: assembleRecordBatch([dictionaryColumn], i, codec)
        });
      }
      idMap.set(dictionaryColumn.type, id);
    } else {
      idMap.set(dictionaryColumn.type, dictMap.get(dictionaryColumn));
    }
  };

  // recurse through column batches to find dictionaries
  // it is sufficient to visit the first batch only,
  // as all batches have the same dictionary column
  columns.forEach(col => visitDictionaries(col.data[0], visitor));

  return { dictionaries, idMap };
}

/**
 * Traverse column batches to visit dictionary columns.
 * @param {Batch} batch
 * @param {(column: Column) => void} visitor
 */
function visitDictionaries(batch, visitor) {
  if (batch?.type.typeId === Type.Dictionary) {
    // @ts-ignore - batch has type DictionaryBatch
    const dictionary = batch.dictionary;
    visitor(dictionary);
    visitDictionaries(dictionary.data[0], visitor);
  }
  batch?.children?.forEach(child => visitDictionaries(child, visitor));
}

/**
 * Assemble a schema with resolved dictionary ids.
 * @param {Schema} schema The schema.
 * @param {Map<DataType, number>} idMap A map
 *  from dictionary value types to dictionary ids.
 * @returns {Schema} A new schema with resolved
 *  dictionary ids. If there are no dictionaries, the input schema is
 *  returned unchanged.
 */
function assembleSchema(schema, idMap) {
  // early exit if no dictionaries
  if (!idMap.size) return schema;

  const visit = type => {
    if (type.typeId === Type.Dictionary) {
      type.id = idMap.get(type.dictionary); // lookup and set id
      visitDictType(type);
    }
    if (type.children) {
      (type.children = type.children.slice()).forEach(visitFields);
    }
  };

  // visit a field in a field array
  const visitFields = (field, index, array) => {
    const type = { ...field.type };
    array[index] = { ...field, type };
    visit(type);
  };

  // visit a dictionary values type
  const visitDictType = (parentType) => {
    const type = { ...parentType.dictionary };
    parentType.dictionary = type;
    visit(type);
  };

  schema = { ...schema, fields: schema.fields.slice() };
  schema.fields.forEach(visitFields);
  return schema;
}

/**
 * Assemble record batches with marshalled buffers.
 * @param {Column[]} columns The table columns.
 * @param {Codec} [codec] Optional buffer compression codec.
 * @returns {RecordBatch[]} The assembled record batches.
 */
function assembleRecordBatches(columns, codec) {
  return (columns[0]?.data || [])
    .map((_, index) => assembleRecordBatch(columns, index, codec));
}

/**
 * Assemble a record batch with marshalled buffers.
 * @param {Column[]} columns The table columns.
 * @param {number} batchIndex The batch index.
 * @param {Codec} [codec] Optional buffer compression codec.
 * @returns {RecordBatch} The assembled record batch.
 */
function assembleRecordBatch(columns, batchIndex = 0, codec) {
  const ctx = assembleContext(codec);
  columns.forEach(column => {
    visit(column.type, column.data[batchIndex], ctx);
  });
  return ctx.done();
}

/**
 * Visit a column batch, assembling buffer data.
 * @param {DataType} type The data type.
 * @param {Batch} batch The column batch.
 * @param {ReturnType<assembleContext>} ctx The assembly context.
 */
function visit(type, batch, ctx) {
  const { typeId } = type;

  // record field node info - ALL fields need field nodes, including nulls
  ctx.node(batch.length, batch.nullCount);

  // null fields have field nodes but no data buffers
  if (typeId === Type.Null) return;

  switch (typeId) {
    // validity and value buffers
    // backing dictionaries handled elsewhere
    case Type.Bool:
    case Type.Int:
    case Type.Time:
    case Type.Duration:
    case Type.Float:
    case Type.Date:
    case Type.Timestamp:
    case Type.Decimal:
    case Type.Interval:
    case Type.FixedSizeBinary:
    case Type.Dictionary: // dict key values
      ctx.buffer(batch.validity);
      ctx.buffer(batch.values);
      return;

    // validity, offset, and value buffers
    case Type.Utf8:
    case Type.LargeUtf8:
    case Type.Binary:
    case Type.LargeBinary:
      ctx.buffer(batch.validity);
      ctx.buffer(batch.offsets);
      ctx.buffer(batch.values);
      return;

    // views with variadic buffers
    case Type.BinaryView:
    case Type.Utf8View:
      ctx.buffer(batch.validity);
      ctx.buffer(batch.values);
      // @ts-ignore
      ctx.variadic(batch.data.length);
      // @ts-ignore
      batch.data.forEach(b => ctx.buffer(b));
      return;

    // validity, offset, and list child
    case Type.List:
    case Type.LargeList:
    case Type.Map:
      ctx.buffer(batch.validity);
      ctx.buffer(batch.offsets);
      ctx.children(type, batch);
      return;

    // validity, offset, size, and list child
    case Type.ListView:
    case Type.LargeListView:
      ctx.buffer(batch.validity);
      ctx.buffer(batch.offsets);
      ctx.buffer(batch.sizes);
      ctx.children(type, batch);
      return;

    // validity and children
    case Type.FixedSizeList:
    case Type.Struct:
      ctx.buffer(batch.validity);
      ctx.children(type, batch);
      return;

    // children only
    case Type.RunEndEncoded:
      ctx.children(type, batch);
      return;

    // union
    case Type.Union: {
      // @ts-ignore
      ctx.buffer(batch.typeIds);
      if (type.mode === UnionMode.Dense) {
        ctx.buffer(batch.offsets);
      }
      ctx.children(type, batch);
      return;
    }

    // unsupported type
    default:
      throw new Error(invalidDataType(typeId));
  }
}
