// © Copyright 2025-2026, Query.Farm LLC - https://query.farm
// SPDX-License-Identifier: Apache-2.0

// Runtime-agnostic exports shared by every entry point. This module MUST NOT
// (transitively) import node-only APIs (node:net/fs/child_process), so it can
// be bundled for Cloudflare Workers / browsers via `./index.workerd.ts`. The
// AF_UNIX launcher (node-only) is added on top of this in `./index.ts` for the
// node/bun barrel; CF builds get this core without it.

export {
  AccessLogHook,
  type AccessLogOptions,
  AccessLogSampler,
  type AccessLogSink,
  type ClaimRedactor,
  FdSink,
  noRedaction,
  otelTraceContext,
  REDACTED,
  redactClaims,
  type TraceContext,
  type TraceContextResolver,
} from "./access-log.js";
export { AuthContext } from "./auth.js";
export * from "./client/index.js";
export {
  ERROR_CODE_KEY,
  ERROR_DETAILS_KEY,
  ERROR_KIND_KEY,
  LOG_EXTRA_KEY,
  LOG_LEVEL_KEY,
  LOG_MESSAGE_KEY,
  REQUEST_ID_KEY,
  REQUEST_VERSION,
  REQUEST_VERSION_KEY,
  RPC_ERROR_HEADER,
  RPC_METHOD_KEY,
  SERVER_ID_KEY,
  STATE_KEY,
} from "./constants.js";
export {
  type BadRequest,
  badRequest,
  decodeErrorDetails,
  ERROR_CODES,
  type ErrorCode,
  type ErrorDetail,
  type ErrorDetailJson,
  type ErrorInfo,
  encodeErrorDetails,
  errorCodeOf,
  errorDetailsOf,
  errorInfo,
  errorKindOf,
  type FieldViolation,
  type Help,
  type HelpLink,
  isErrorCode,
  isRetryable,
  type LocalizedMessage,
  MAX_ERROR_DETAILS_BYTES,
  type PreconditionFailure,
  type PreconditionViolation,
  parseErrorCode,
  parseErrorDetail,
  preconditionFailure,
  type QuotaFailure,
  type QuotaViolation,
  type ResourceInfo,
  type RetryInfo,
  retryInfo,
  StatusError,
  type StatusErrorOptions,
} from "./error-model.js";
export {
  ERROR_KIND_METHOD_NOT_IMPLEMENTED,
  ERROR_KIND_SERVER_DRAINING,
  ERROR_KIND_SESSION_LOST,
  MethodNotImplementedError,
  ProtocolVersionError,
  ResponseTooLargeError,
  RpcError,
  type RpcErrorModel,
  ServerDrainingError,
  SessionLostError,
  VersionError,
} from "./errors.js";
export {
  type ExternalLocationConfig,
  ExternalRef,
  type ExternalStorage,
  httpsOnlyValidator,
  isExternalLocationBatch,
  isExternalRef,
  makeExternalLocationBatch,
  maybeExternalizeBatch,
  type PublishExternalOptions,
  publishExternal,
  publishExternalResult,
  resolveExternalLocation,
} from "./external.js";
// Sealed grants (WIRE_PROTOCOL.md §16): mint/verify, and the bearer
// authenticators that accept grants and resolveToken credentials.
export {
  DEFAULT_GRANT_CLOCK_SKEW_SECONDS,
  DEFAULT_GRANT_MAX_TTL_SECONDS,
  GRANT_AUDIENCE_ENV,
  GRANT_KEYS_ENV,
  GRANT_MAX_TTL_ENV,
  GRANT_TOKEN_PREFIX,
  type GrantClaims,
  GrantInvalidError,
  GrantKeys,
  type GrantKeysOptions,
  grantKeyId,
  MAX_GRANT_TOKEN_CHARS,
  type MintedGrant,
  type MintGrantRequest,
  mintGrantToken,
  sealedMintGrant,
  verifyGrantToken,
} from "./grants.js";
export {
  composeIdentityAuthenticate,
  GRANT_AUTH_DOMAIN,
  GrantRejectedError,
  grantAuthenticate,
  type IdentityBearerSources,
  resolveTokenAuthenticate,
  TOKEN_AUTH_DOMAIN,
} from "./http/grant-auth.js";
export {
  ARROW_CONTENT_TYPE,
  AUTH_PROXY_REQUIRED_HEADER,
  AUTH_REASON_HEADER,
  type AuthenticateFn,
  AuthFailure,
  AuthReason,
  AuthUnavailableError,
  type AwsAlbSpiffeOptions,
  awsAlbSpiffeProvider,
  azureApplicationGatewaySpiffeProvider,
  type BearerValidateFn,
  bearerAuthenticate,
  bearerAuthenticateStatic,
  type CertificateProxySpiffeOptions,
  type CertValidateFn,
  chainAuthenticate,
  createHttpHandler,
  decodeContentEncoding,
  type EnvoyXfccSpiffeOptions,
  type ExtraRouteContext,
  type ExtraRouteHandler,
  envoyXfccSpiffeProvider,
  type GcpLoadBalancerSpiffeOptions,
  gcpLoadBalancerSpiffeProvider,
  type HttpHandlerOptions,
  headersFromNodeRawHeaders,
  type JwtAuthenticateOptions,
  jsonStateSerializer,
  jwtAuthenticate,
  MAX_UPLOAD_URL_COUNT,
  mtlsAuthenticate,
  mtlsAuthenticateFingerprint,
  mtlsAuthenticateSubject,
  mtlsAuthenticateXfcc,
  nginxSpiffeProvider,
  type OAuthResourceMetadata,
  oauthResourceMetadataToJson,
  parseXfcc,
  reservedPath,
  rpcPath,
  rpcPathFromPrefix,
  SERVER_SCOPE,
  type SpiffeX509HeaderProviderOptions,
  type StateSerializer,
  spiffeX509HeaderProvider,
  type TokenScope,
  type UnpackedToken,
  UPLOAD_URL_METHOD,
  UPLOAD_URL_PARAMS_SCHEMA,
  UPLOAD_URL_RESPONSE_SCHEMA,
  unpackStateToken,
  validateSpiffeId,
  type XfccElement,
  type XfccValidateFn,
} from "./http/index.js";
export {
  allOfPeerIdentities,
  anyOfPeerIdentities,
  IdentityAssurance,
  type JsonValue,
  observePeerIdentity,
  type PeerAuthenticationPolicy,
  PeerEvidenceSet,
  PeerIdentity,
  type PeerIdentityLinker,
  type PeerIdentityOptions,
  type PeerIdentityProvider,
  PeerIdentityRejectedError,
  PeerIdentityResult,
  PeerIdentityStatus,
  PeerIdentityUnavailableError,
  PeerResolutionContext,
  type PeerResolutionOptions,
  PeerSubjectKind,
  peerIdentityPrimary,
  requirePeerIdentity,
  SubjectStability,
} from "./identity.js";
export {
  IROH_FORWARDED_ENDPOINT_HEADER,
  type IrohForwardedHeaderOptions,
  type IrohHttpBridgeOptions,
  type IrohHttpHandlerOptions,
  irohForwardedHeaderIdentityProvider,
  irohHttpBridgeOptions,
} from "./iroh.js";
export { Protocol } from "./protocol.js";
export {
  bool,
  bytes,
  float,
  float32,
  inferParamTypes,
  int,
  int8,
  int16,
  int32,
  type SchemaLike,
  str,
  toSchema,
  uint8,
  uint16,
  uint32,
  uint64,
} from "./schema.js";
export { type ServeStreamOptions, serveStream } from "./serve-stream.js";
export { type RawPeer, VgiRpcServer, type VgiRpcServerOptions } from "./server.js";
// `vgi_rpc.Identity.v1` -- the framework-owned identity protocol, and the only
// introspection surface: the HTTP `__introspect_token__` route it replaced is
// retired (IDENTITY_V1_SPEC §8).
export {
  buildIdentityProtocol,
  checkFreshness,
  checkIntrospector,
  DEFAULT_IDENTITY_TTL_SECONDS,
  DEFAULT_MAX_AUTH_AGE_SECONDS,
  encodeIssuedGrant,
  encodeTokenIdentity,
  type GrantMinter,
  GrantRefusedError,
  IDENTITY_PROTOCOL_NAME,
  IdentityImpl,
  type IdentityOptions,
  IdentityUnavailableError,
  IntrospectionRefusedError,
  ISSUED_GRANT_SCHEMA,
  type IssuedGrant,
  isJwsShaped,
  MAX_TOKEN_BYTES,
  normalisePrincipals,
  rejectJwsShaped,
  StaleAuthError,
  TOKEN_IDENTITY_SCHEMA,
  type TokenIdentity,
  type TokenResolver,
  TokenUnresolvedError,
  tokenDigest,
  trimForShapeTest,
  utf8Length,
} from "./token-identity.js";
export {
  type AccessLogDeferral,
  type CallContext,
  type CallStatistics,
  type DispatchHook,
  type DispatchInfo,
  type ExchangeFn,
  type ExchangeInit,
  type HeaderInit,
  type HookToken,
  type LogContext,
  type MethodDefinition,
  MethodType,
  OutputCollector,
  type ProducerFn,
  type ProducerInit,
  type ServeStartHook,
  TransportKind,
  type UnaryHandler,
} from "./types.js";
export {
  buildErrorStream,
  findProtocolVersion,
  findStateToken,
  readRequest,
  readUnaryResult,
  type UnaryResult,
  type WireRequest,
  writeRequest,
  writeUnaryResult,
} from "./wire/public.js";
export type { ByteSink } from "./wire/writer.js";
